version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  backend:
    build: ./backend
    container_name: graphql_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo_data: